/**
 * The 64 emoji Matrix uses for SAS verification, in its order, with its English names.
 * The index is what the bits pick, so the order is part of the protocol. Never reorder it.
 */

export interface PairingEmoji {
  readonly emoji: string;
  readonly name: string;
}

export const PAIRING_EMOJI: readonly PairingEmoji[] = Object.freeze([
  { emoji: "🐶", name: "Dog" },
  { emoji: "🐱", name: "Cat" },
  { emoji: "🦁", name: "Lion" },
  { emoji: "🐎", name: "Horse" },
  { emoji: "🦄", name: "Unicorn" },
  { emoji: "🐷", name: "Pig" },
  { emoji: "🐘", name: "Elephant" },
  { emoji: "🐰", name: "Rabbit" },
  { emoji: "🐼", name: "Panda" },
  { emoji: "🐓", name: "Rooster" },
  { emoji: "🐧", name: "Penguin" },
  { emoji: "🐢", name: "Turtle" },
  { emoji: "🐟", name: "Fish" },
  { emoji: "🐙", name: "Octopus" },
  { emoji: "🦋", name: "Butterfly" },
  { emoji: "🌷", name: "Flower" },
  { emoji: "🌳", name: "Tree" },
  { emoji: "🌵", name: "Cactus" },
  { emoji: "🍄", name: "Mushroom" },
  { emoji: "🌏", name: "Globe" },
  { emoji: "🌙", name: "Moon" },
  { emoji: "☁\ufe0f", name: "Cloud" },
  { emoji: "🔥", name: "Fire" },
  { emoji: "🍌", name: "Banana" },
  { emoji: "🍎", name: "Apple" },
  { emoji: "🍓", name: "Strawberry" },
  { emoji: "🌽", name: "Corn" },
  { emoji: "🍕", name: "Pizza" },
  { emoji: "🎂", name: "Cake" },
  { emoji: "❤\ufe0f", name: "Heart" },
  { emoji: "😀", name: "Smiley" },
  { emoji: "🤖", name: "Robot" },
  { emoji: "🎩", name: "Hat" },
  { emoji: "👓", name: "Glasses" },
  { emoji: "🔧", name: "Spanner" },
  { emoji: "🎅", name: "Santa" },
  { emoji: "👍", name: "Thumbs Up" },
  { emoji: "☂\ufe0f", name: "Umbrella" },
  { emoji: "⌛", name: "Hourglass" },
  { emoji: "⏰", name: "Clock" },
  { emoji: "🎁", name: "Gift" },
  { emoji: "💡", name: "Light Bulb" },
  { emoji: "📕", name: "Book" },
  { emoji: "✏\ufe0f", name: "Pencil" },
  { emoji: "📎", name: "Paperclip" },
  { emoji: "✂\ufe0f", name: "Scissors" },
  { emoji: "🔒", name: "Lock" },
  { emoji: "🔑", name: "Key" },
  { emoji: "🔨", name: "Hammer" },
  { emoji: "☎\ufe0f", name: "Telephone" },
  { emoji: "🏁", name: "Flag" },
  { emoji: "🚂", name: "Train" },
  { emoji: "🚲", name: "Bicycle" },
  { emoji: "✈\ufe0f", name: "Aeroplane" },
  { emoji: "🚀", name: "Rocket" },
  { emoji: "🏆", name: "Trophy" },
  { emoji: "⚽", name: "Ball" },
  { emoji: "🎸", name: "Guitar" },
  { emoji: "🎺", name: "Trumpet" },
  { emoji: "🔔", name: "Bell" },
  { emoji: "⚓", name: "Anchor" },
  { emoji: "🎧", name: "Headphones" },
  { emoji: "📁", name: "Folder" },
  { emoji: "📌", name: "Pin" },
]);
